name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build and test
      run: bash native_lib/build-cmdline.sh
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: native_lib/test_user_setup
