name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: make dist-ci
    - run: make test

  test_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Action
        id: action
        uses: ./action/
        with:
          dry-run: 'false'
          debug: 'true'
      - run: echo "::notice title=recovery code::${{ steps.action.outputs.recovery-code }}"
