name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_cli:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: make dist-ci
    - run: make test

  test_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./action/
      - run: echo "Recovery code is '${{ steps.action.outputs.recovery-code }}'."
